### ISSUE TITLE
arguments?

### ISSUE THREAD

**Issue by GerardWassink** [mgrossmann/brexx370#11]
I tried to do 'rx primes 100' and it complains about the argument which it was supposed to read.
Is this going to be solved shortly?

**Comment by mgrossmann** [comment]
This problem will be fixed in the next release.
RX is a CLIST. We currently need a CLIST as a wrapper to enable the exchange of variables between REXX and ISPF in the ISPF environment and to allocate the REXX script to be started. The pre-allocation of REXX scripts will no longer be necessary in the next release. This means that in the next release you can call REXX scripts directly via [B]REXX _DSN,DDN,MEMBER_. The RX wrapper will then only be needed for ISPF. More details will be documented in the release notes.

Translated with www.DeepL.com/Translator
