### ISSUE TITLE
Dataset not found messages

### ISSUE THREAD

**Issue by JohanDees** [mgrossmann/brexx370#29]
While executing a BREXX programm it looks in private dataset first for the library files.
MVS TK4 generates an error:

IEC141I 013-18,IGG0191B,TNMVS,IKJACCNT,JCC00003,281,PUB012,

It does this for every library file search and is annoying.

The file is eventually found, and there is no reason for error messages to the user, beacuse there is no error.

It also disturbs the beautifull flawless execution on the screen...  :-(

I suggest to look in RXLIB first, and then in the user libraries. Otherwise every user must have a copy of RXLIB, and thats is not managable.

Johan

**Comment by mgrossmann** [comment]
Hello, Johan,

IEC141I 013-18 is not an error message, but an info message. But of course you are right, it is very unsatisfying that this message appears all the time.  
We have intentionally chosen this current search order since we want to keep close to the behavior of REXX under z/OS. 
But @Peter-Jacob  and I are aware of the problem and will try to find a suitable solution.

Mike

**Comment by mgrossmann** [comment]
Hi @JohanDees 

we have now changed the search order for the function imports. First, the RXLIB allocation is searched. If the function is not found there, we search at the location of the currently executed script.
